definitions:
  models.CarbonElectricRequest:
    properties:
      electric_id:
        type: integer
      emission_factor:
        type: number
      price:
        type: number
      usage_amount:
        type: number
      usage_type:
        enum:
        - consumption
        - rupiah
        type: string
      user_id:
        type: integer
    required:
    - electric_id
    - emission_factor
    - price
    - usage_amount
    - usage_type
    - user_id
    type: object
  models.CarbonElectricResponse:
    properties:
      emission_amount:
        type: number
      emission_factor:
        type: number
      id:
        type: integer
      total_consumption:
        type: number
      usage_amount:
        type: number
      usage_type:
        type: string
      user_email:
        type: string
      user_id:
        type: integer
      user_name:
        type: string
    type: object
  models.Electric:
    properties:
      emission_factor:
        type: number
      id:
        type: integer
      price:
        type: number
      province:
        type: string
    type: object
  models.Role:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.RoleRequest:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /carbon-electrics:
    get:
      consumes:
      - application/json
      description: Retrieve a list of carbon electric entries for the logged-in user
      produces:
      - application/json
      responses:
        "200":
          description: List of carbon electric entries
          schema:
            items:
              $ref: '#/definitions/models.CarbonElectricResponse'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all carbon electrics
      tags:
      - CarbonElectrics
    post:
      consumes:
      - application/json
      description: Add a new carbon electric entry for the logged-in user
      parameters:
      - description: Carbon Electric request body
        in: body
        name: carbonElectricRequest
        required: true
        schema:
          $ref: '#/definitions/models.CarbonElectricRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created carbon electric entry
          schema:
            $ref: '#/definitions/models.CarbonElectricResponse'
        "400":
          description: Invalid request payload or usage type/amount
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new carbon electric entry
      tags:
      - CarbonElectrics
  /carbon-electrics/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a specific carbon electric entry by its unique ID
      parameters:
      - description: Carbon Electric ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted carbon electric entry
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid carbon electric ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Carbon electric not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a carbon electric entry
      tags:
      - CarbonElectrics
    get:
      consumes:
      - application/json
      description: Fetch details of a specific carbon electric entry by its unique
        ID
      parameters:
      - description: Carbon Electric ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Carbon electric entry details
          schema:
            $ref: '#/definitions/models.CarbonElectricResponse'
        "400":
          description: Invalid carbon electric ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Carbon electric not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a carbon electric entry by ID
      tags:
      - CarbonElectrics
  /electrics:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all electric records
      produces:
      - application/json
      responses:
        "200":
          description: List of electrics
          schema:
            items:
              $ref: '#/definitions/models.Electric'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get all electric data
      tags:
      - Electrics
    post:
      consumes:
      - application/json
      description: Add a new electric record to the database
      parameters:
      - description: Electric data
        in: body
        name: electric
        required: true
        schema:
          $ref: '#/definitions/models.Electric'
      produces:
      - application/json
      responses:
        "201":
          description: Created electric
          schema:
            $ref: '#/definitions/models.Electric'
        "400":
          description: Invalid request payload
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Create a new electric record
      tags:
      - Electrics
  /electrics/{id}:
    delete:
      consumes:
      - application/json
      description: Remove an electric record from the database
      parameters:
      - description: Electric ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Electric deleted successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid electric ID
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Delete an electric record by ID
      tags:
      - Electrics
    get:
      consumes:
      - application/json
      description: Fetch an electric record using its unique ID
      parameters:
      - description: Electric ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Electric details
          schema:
            $ref: '#/definitions/models.Electric'
        "400":
          description: Invalid electric ID
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Electric not found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get an electric record by ID
      tags:
      - Electrics
    put:
      consumes:
      - application/json
      description: Modify the details of an existing electric record
      parameters:
      - description: Electric ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated electric data
        in: body
        name: electric
        required: true
        schema:
          $ref: '#/definitions/models.Electric'
      produces:
      - application/json
      responses:
        "200":
          description: Updated electric
          schema:
            $ref: '#/definitions/models.Electric'
        "400":
          description: Invalid electric ID or payload
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Update an electric record by ID
      tags:
      - Electrics
  /roles:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all roles
      produces:
      - application/json
      responses:
        "200":
          description: List of roles
          schema:
            items:
              $ref: '#/definitions/models.Role'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all roles
      tags:
      - Roles
    post:
      consumes:
      - application/json
      description: Add a new role to the system
      parameters:
      - description: Role request payload
        in: body
        name: roleRequest
        required: true
        schema:
          $ref: '#/definitions/models.RoleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created role
          schema:
            $ref: '#/definitions/models.Role'
        "400":
          description: Invalid request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new role
      tags:
      - Roles
  /roles/{id}:
    delete:
      consumes:
      - application/json
      description: Remove a specific role by its unique ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted role
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid role ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Role not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a role
      tags:
      - Roles
    get:
      consumes:
      - application/json
      description: Retrieve details of a specific role by its unique ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Role details
          schema:
            $ref: '#/definitions/models.Role'
        "400":
          description: Invalid role ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Role not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a role by ID
      tags:
      - Roles
    put:
      consumes:
      - application/json
      description: Update details of an existing role by its unique ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      - description: Role update request payload
        in: body
        name: roleRequest
        required: true
        schema:
          $ref: '#/definitions/models.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated role
          schema:
            $ref: '#/definitions/models.Role'
        "400":
          description: Invalid role ID or request payload
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Role not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a role
      tags:
      - Roles
swagger: "2.0"
