name: GoLang CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies and run tests
        run: |
          go mod tidy
          go test ./...

      - name: Check secrets
        run: |
          echo "GOOGLE_PROJECT_ID: persuasive-axe-317613"
          echo "GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}"
        
      - name: Debug environment
        run: |
          echo $SHELL
          echo $GITHUB_SHA

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx version

      - name: Build Docker image
        run: |
          docker buildx build -t gcr.io/persuasive-axe-317613/carbon-api:$GITHUB_SHA .

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Configure Google Cloud CLI
      - name: Set up gcloud CLI
        run: |
          gcloud --quiet config set project persuasive-axe-317613
          gcloud --quiet config set compute/region us-central1
          gcloud --quiet config set compute/zone us-central1-a

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy api \
            --image gcr.io/persuasive-axe-317613/carbon-api:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

      - name: Build Docker image
        run: |
          docker build -t gcr.io/persuasive-axe-317613/carbon-api:latest .
        
      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/persuasive-axe-317613/carbon-api:latest