name: GoLang CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - "6379:6379"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies and run tests
        run: |
          go mod tidy
          go test ./...

      - name: Check secrets
        run: |
          echo "GOOGLE_PROJECT_ID: persuasive-axe-317613"
          echo "GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}"

      - name: Debug environment
        run: |
          echo "Current shell: $SHELL"
          echo "Commit SHA: $GITHUB_SHA"
          echo "GO version: $(go version)"

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx version

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker

      - name: Build Docker Compose environment
        run: |
          docker-compose -f docker-compose.yml build

      - name: Build and Push Docker image to GCR
        run: |
          docker-compose push

      - name: Set up gcloud CLI
        run: |
          gcloud --quiet config set project persuasive-axe-317613
          gcloud --quiet config set compute/region us-central1
          gcloud --quiet config set compute/zone us-central1-a

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy carbon-api \
            --image gcr.io/persuasive-axe-317613/carbon-api:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --timeout 10m
