name: GoLang CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies and run tests
        run: |
          go mod tidy
          go test ./...

  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx version

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker image to GCR
        run: |
          docker buildx build -t gcr.io/persuasive-axe-317613/carbon-api:latest --push .

      - name: Set up gcloud CLI
        run: |
          gcloud --quiet config set project persuasive-axe-317613
          gcloud --quiet config set compute/region us-central1
          gcloud --quiet config set compute/zone us-central1-a

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy carbon-api \
            --image gcr.io/persuasive-axe-317613/carbon-api:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --timeout 10m
              --set-secrets \
                "API_PORT=projects/persuasive-axe-317613/secrets/API_PORT/versions/latest" \
                "PORT=projects/persuasive-axe-317613/secrets/PORT/versions/latest" \
                "BASE_URL=projects/persuasive-axe-317613/secrets/BASE_URL/versions/latest" \
                "DATABASE_URL=projects/persuasive-axe-317613/secrets/DATABASE_URL/versions/latest" \
                "REDIS_URL=projects/persuasive-axe-317613/secrets/REDIS_URL/versions/latest" \
                "MONGODB_URI=projects/persuasive-axe-317613/secrets/MONGODB_URI/versions/latest" \
                "MONGO_DATABASE=projects/persuasive-axe-317613/secrets/MONGO_DATABASE/versions/latest" \
                "MONGO_COLLECTION=projects/persuasive-axe-317613/secrets/MONGO_COLLECTION/versions/latest" \
                "SMTP_HOST=projects/persuasive-axe-317613/secrets/SMTP_HOST/versions/latest" \
                "SMTP_PORT=projects/persuasive-axe-317613/secrets/SMTP_PORT/versions/latest" \
                "SMTP_USERNAME=projects/persuasive-axe-317613/secrets/SMTP_USERNAME/versions/latest" \
                "SMTP_PASSWORD=projects/persuasive-axe-317613/secrets/SMTP_PASSWORD/versions/latest" \
                "JWT_SECRET=projects/persuasive-axe-317613/secrets/JWT_SECRET/versions/latest" \
                "XENDIT_API_URL=projects/persuasive-axe-317613/secrets/XENDIT_API_URL/versions/latest" \
                "XENDIT_SECRET_KEY=projects/persuasive-axe-317613/secrets/XENDIT_SECRET_KEY/versions/latest" \
                "GEMINI_API_KEY=projects/persuasive-axe-317613/secrets/GEMINI_API_KEY/versions/latest" \
                "OPENAI_API_KEY=projects/persuasive-axe-317613/secrets/OPENAI_API_KEY/versions/latest"
