name: GoLang CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} 
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies and run tests
        run: |
          go mod tidy
          go test ./...

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx version

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker

      - name: Build and Push Docker image to GCR
        run: |
          docker buildx build -t gcr.io/persuasive-axe-317613/carbon-api:latest --push .

      - name: Set up gcloud CLI
        run: |
          gcloud --quiet config set project persuasive-axe-317613
          gcloud --quiet config set compute/region us-central1
          gcloud --quiet config set compute/zone us-central1-a

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy carbon-api \
            --image gcr.io/persuasive-axe-317613/carbon-api:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --timeout 10m \
            --set-secrets API_PORT=API_PORT:latest \
            --set-secrets BASE_URL=BASE_URL:latest \
            --set-secrets DATABASE_URL=DATABASE_URL:latest \
            --set-secrets REDIS_URL=REDIS_URL:latest \
            --set-secrets MONGODB_URI=MONGODB_URI:latest \
            --set-secrets MONGO_DATABASE=MONGO_DATABASE:latest \
            --set-secrets MONGO_COLLECTION=MONGO_COLLECTION:latest \
            --set-secrets SMTP_HOST=SMTP_HOST:latest \
            --set-secrets SMTP_PORT=SMTP_PORT:latest \
            --set-secrets SMTP_USERNAME=SMTP_USERNAME:latest \
            --set-secrets SMTP_PASSWORD=SMTP_PASSWORD:latest \
            --set-secrets JWT_SECRET=JWT_SECRET:latest \
            --set-secrets XENDIT_API_URL=XENDIT_API_URL:latest \
            --set-secrets XENDIT_SECRET_KEY=XENDIT_SECRET_KEY:latest \
            --set-secrets GEMINI_API_KEY=GEMINI_API_KEY:latest \
            --set-secrets OPENAI_API_KEY=OPENAI_API_KEY:latest
